---
title: "Crash Course on Linear Mixed Models"
description: |
  This post is intended as a crash course introduction on LMMs based on how I would have liked to learn the basics of LMMs if I were to learn it from scratch. I am by no means an expert on LMMs, and thus, some information given here might be inaccurate, but where possible, i will cite appropriate papers and books to help assist in further reading and learning
author:
  - name: Jonathan Choo
    Affiliation: University of Nottingham, Malaysia
date: 2022-08-09
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Welcome to a crash course on Linear Mixed Models (LMMs)! There are slight variations in the naming conventions of LMMs, you may encounter Linear Mixed Efffect Models, Mixed Models, Multi-level Models, rest assured, these all refer to the same concept that we will be going through today.

Before we proceed, this course assumes that the reader has:

1. Basics in Statistics in Psychology
  - Specifically Regression Analysis and Analysis of Variance (ANOVA)
2. Basics of R language
3. Basics of Data Structure and Organization

_If you are not knowledgeable in these areas, it is highly recommended that you brush up on these skills before attempting this course._

Have everything? Great! Let us start off with introducing what LMEs are

## LMEs: The Whats and the Whys

#### What

LMEs are essentially a regression analysis on steroids, providing the flexibility of traditional regression analysis, but allowing for more accurate model fitting compared to regular variance analysis like ANOVA. It achieves this flexibility by introducing two types of effects: **1) Fixed Effects** and **2) Random Effects** - hence the name "mixed model", as it includes both of these effects, rather than a traditional Fixed-Effects only model like ANOVAs.

Understanding Fixed Effects and Random Effects is crucial in running an LME analysis. To understand what these effects are, [Freeman (2017)](http://mfviz.com/hierarchical-models/) provides an excellent overview along with a beautifully animated visualization on Fixed Effects and Random Effects.

*It may take a while for the embedded page to load, alternatively, head over to [Freeman's (2017)](http://mfviz.com/hierarchical-models/) page to view it*

<iframe width='1000px' height='1000px' src='http://mfviz.com/hierarchical-models/' ></iframe>

